import { Era } from "../types";

export const ERAS: Era[] = [
  {
    id: 'ancient-egypt',
    name: 'Ancient Egypt',
    description: 'Walk among pharaohs and pyramids.',
    prompt: 'Cinematic masterpiece, Ancient Egypt, 1300 BC. The subject is a Pharaoh or High Priestess, adorned in a translucent pleated kalasiris of fine white linen, a heavy gold Wesekh collar inlaid with turquoise and lapis lazuli, and a nemes headcloth or vulture headdress. Their skin glows with golden warmth, eyes accented by sharp kohl lines. Background: The grand hypostyle hall of Karnak, massive sandstone columns carved with hieroglyphs rising into shadow, shafts of golden sunlight piercing through the dust, incense smoke swirling in the air, the Nile river glittering in the distance, hyper-realistic, 8k resolution, volumetric lighting.',
    icon: '🐫',
  },
  {
    id: 'victorian-london',
    name: 'Victorian London',
    description: 'Steam, fog, and top hats.',
    prompt: 'Cinematic shot, Victorian London, 1890. The subject is an English gentleman or lady, dressed in authentic period attire: a charcoal wool frock coat, a silk top hat, and a pocket watch chain, or a bustle dress with lace gloves and a bonnet. Background: A cobblestone street shrouded in thick, swirling fog (pea-souper), illuminated by the warm, flickering yellow glow of gas streetlamps. The silhouette of Big Ben and the Houses of Parliament looms in the distance. Moody atmospheric lighting, wet pavement reflecting the lights, mysterious ambiance, 8k resolution, highly detailed textures.',
    icon: '🎩',
  },
  {
    id: 'roaring-20s',
    name: 'Roaring 20s',
    description: 'Jazz, glitz, and glamour.',
    prompt: 'Cinematic shot, New York City, 1925. The subject is the epitome of Jazz Age glamour, dressed in a sparkling sequined flapper dress with fringe and a feathered headband, or a sharp black tuxedo with a bow tie. Background: An opulent Art Deco ballroom filled with golden confetti raining down, crystal chandeliers dripping with light, and a vibrant party atmosphere. Champagne towers, geometric gold patterns, high contrast, cinematic lighting, sharp focus, capturing the energy of the era.',
    icon: '🎷',
  },
  {
    id: 'cyberpunk-2099',
    name: 'Cyberpunk 2099',
    description: 'Neon lights and chrome.',
    prompt: 'Cinematic shot, Neo-Tokyo, 2099. The subject is a futuristic cyberpunk edgerunner, featuring subtle cybernetic implants, glowing circuitry on skin, and high-tech tactical streetwear with LED accents. Background: A rainy, grimy alleyway drenched in neon pink and cyan light, towering skyscrapers with holographic advertisements reflecting in rain puddles, flying cars zooming overhead with light trails. Gritty sci-fi aesthetic, ray tracing, 8k resolution, wet surfaces, atmospheric smoke.',
    icon: '🤖',
  },
  {
    id: 'medieval-fantasy',
    name: 'Medieval Fantasy',
    description: 'Knights, dragons, and magic.',
    prompt: 'Cinematic shot, High Fantasy Realm. The subject is an epic hero, clad in intricate, battle-worn silver plate armor engraved with runes, wearing a fur-lined cloak and holding a glowing magical staff or sword. Background: A majestic stone castle perched precariously on a jagged cliffside, a dragon soaring through storm clouds in the distance, dramatic overcast sky with shafts of light. Magical atmosphere, volumetric lighting, detailed metal and fabric textures, Lord of the Rings aesthetic.',
    icon: '⚔️',
  },
  {
    id: 'wild-west',
    name: 'Wild West',
    description: 'Cowboys and dusty saloons.',
    prompt: 'Cinematic shot, American Frontier, 1870. The subject is a rugged gunslinger or outlaw, wearing a weathered leather duster coat, a worn cowboy hat, a bandana around the neck, and a gun belt with revolvers. Background: A dusty wooden boardwalk outside a saloon in a frontier town, tumbleweeds rolling by, wooden facades, hitching posts. Warm, harsh afternoon sun casting long, dramatic shadows. Western film aesthetic, sepia undertones, 8k resolution, gritty texture.',
    icon: '🤠',
  },
  {
    id: 'feudal-japan',
    name: 'Feudal Japan',
    description: 'Samurai, cherry blossoms, and honor.',
    prompt: 'Cinematic shot, Kyoto, 1600. The subject is a noble samurai warrior wearing intricate lacquered o-yoroi armor with gold detailing and a katana at the waist, or a figure in a fine silk kimono with embroidered floral patterns. Background: A serene Zen garden with a red torii gate, stone lanterns, and pink cherry blossom petals falling gently in the breeze. Traditional pagoda architecture in the background. Soft, diffused lighting, peaceful and elegant atmosphere, photorealistic, depth of field.',
    icon: '🏯',
  },
  {
    id: 'neon-80s',
    name: 'Neon 80s',
    description: 'Synthwave, arcades, and big hair.',
    prompt: 'Cinematic shot, 1985 Arcade. The subject is an 80s icon, wearing a stonewashed denim jacket with patches, neon-colored accessories, fingerless gloves, and voluminous hair. Background: A retro arcade interior filled with glowing CRT cabinets, neon signs (PAC-MAN, GALAGA), a checkerboard floor, and a haze of smoke. Vaporwave color palette (magenta, cyan, purple), nostalgic synthwave vibe, high contrast, bloom effects.',
    icon: '🕹️',
  },
  {
    id: 'pirate-age',
    name: 'Pirate High Seas',
    description: 'Ships, treasure, and open seas.',
    prompt: 'Cinematic shot, Caribbean Sea, 1715. The subject is a swashbuckling pirate captain, wearing a weathered tricorn hat, a velvet frock coat, a leather baldric with a flintlock pistol, and loose linen shirt. Background: The wooden deck of a massive galleon ship, rigging and sails billowing in the wind, turquoise ocean water crashing against the hull, a tropical island on the horizon. Bright sunlight, salty atmosphere, adventure style, highly detailed wood and water textures.',
    icon: '🏴‍☠️',
  },
  {
    id: 'viking-saga',
    name: 'Viking Saga',
    description: 'Furs, axes, and longships.',
    prompt: 'Cinematic shot, Norway, 800 AD. The subject is a fierce Viking warrior, wrapped in thick wolf furs and chainmail, holding a battle axe or round shield, with war paint on their face. Background: A misty fjord with steep, snow-capped mountains rising from the dark water, a Viking longship with a dragon prow docked on the rocky shore. Cold, desaturated blue tones, dramatic and raw atmosphere, photorealistic, fog and mist effects.',
    icon: '🪓',
  },
  {
    id: 'renaissance-italy',
    name: 'Renaissance Italy',
    description: 'Art, velvet, and masquerades.',
    prompt: 'Cinematic shot, Venice, 1500. The subject is a Venetian noble, dressed in luxurious velvet Renaissance robes with gold embroidery, a lace ruff, and holding an ornate, feathered masquerade mask. Background: A stone bridge over a Venetian canal at twilight, gondolas gliding by, historic palazzo architecture with arched windows, soft lantern light reflecting on the water. Romantic, mysterious, opulent, 8k resolution, rich colors.',
    icon: '🎭',
  },
  {
    id: 'space-age-60s',
    name: 'Space Age 1960s',
    description: 'Retro-futurism and moon landings.',
    prompt: 'Cinematic shot, 1960s Retro-Future. The subject is an astronaut or space traveler, wearing a sleek, shiny silver space suit with a bubble helmet, white gloves, and go-go boots. Background: A stylized lunar landscape with a massive, detailed Earth rising in the black starry sky, a retro sci-fi rocket ship with fins nearby. Pulp fiction art style, bold primary colors, vintage film grain, technicolor, adventurous and optimistic.',
    icon: '🚀',
  },
  {
    id: 'post-apocalyptic',
    name: 'Wasteland 2050',
    description: 'Survival gear and desert ruins.',
    prompt: 'Cinematic shot, Wasteland, 2050. The subject is a rugged survivor, wearing distressed tactical gear, improvised armor made of tires and scrap metal, goggles, and a scarf to protect against dust. Background: A ruined city skyline reclaimed by vast desert sand dunes, rusted metal structures, harsh, blinding sunlight. Mad Max aesthetic, gritty, realistic, high contrast, heat haze effect, highly detailed textures of rust and sand.',
    icon: '☢️',
  },
  {
    id: 'film-noir',
    name: 'Film Noir 1940s',
    description: 'Shadows, detectives, and mystery.',
    prompt: 'Cinematic shot, 1940s Film Noir. The subject is a private investigator or femme fatale, wearing a trench coat and fedora, or an elegant evening gown, smoking a cigarette. Background: A dark, rainy city street at night, wet pavement reflecting streetlights, shadows cast by venetian blinds. High contrast black and white photography, dramatic chiaroscuro lighting, mysterious and moody atmosphere, film grain.',
    icon: '🕵️',
  },
  {
    id: 'disco-fever',
    name: 'Disco Fever',
    description: 'Groovy moves and disco balls.',
    prompt: 'Cinematic shot, 1977 Disco Club. The subject is the king or queen of the dance floor, wearing a white polyester bell-bottom suit or a shimmering sequined jumpsuit, striking a dynamic dance pose. Background: A multi-colored illuminated dance floor, a giant sparkling disco ball overhead casting light spots everywhere, hazy atmosphere, crowded club. Studio 54 vibe, vibrant, energetic, soft focus, flares.',
    icon: '💃',
  },
  {
    id: 'prehistoric',
    name: 'Prehistoric Wild',
    description: 'Cave furs and dinosaurs.',
    prompt: 'Cinematic shot, Late Cretaceous. The subject is a primitive hunter-gatherer, wearing rough animal pelts and holding a primitive wooden spear with a stone tip. Background: A lush, dense prehistoric jungle with giant ferns and cycads, a massive Triceratops or T-Rex visible in a clearing in the distance. Volumetric lighting filtering through the canopy, epic scale, 8k resolution, realistic textures.',
    icon: '🦕',
  },
  {
    id: 'roman-empire',
    name: 'Roman Empire',
    description: 'Togas, gladiator armor, and marble.',
    prompt: 'Cinematic shot, Ancient Rome, 100 AD. The subject is a Roman Senator in a white toga with a purple border, or a Gladiator in bronze muscle cuirass and helmet. Background: The interior of the Colosseum or the Roman Forum with pristine white marble columns and statues, cheering crowds in the distance. Bright Mediterranean sunlight, clear blue sky, grandeur and history, photorealistic, architectural detail.',
    icon: '🏛️',
  },
  {
    id: 'ww2',
    name: 'World War II',
    description: '1940s Wartime Era.',
    prompt: 'Cinematic shot, Europe, 1944. The subject is a soldier or resistance fighter, dressed in a period-accurate military uniform (khaki or olive drab) or 1940s civilian clothing with a beret. Background: A war-torn European village street with rubble and damaged buildings, or an airfield with a Spitfire plane. Desaturated color palette, gritty realism, emotional depth, cinematic lighting, historical accuracy.',
    icon: '🎖️',
  },
  {
    id: 'ancient-greece',
    name: 'Ancient Greece',
    description: 'Philosophers and marble temples.',
    prompt: 'Cinematic shot, Athens, 400 BC. The subject is a philosopher or citizen, wearing a draped white Greek chiton and leather sandals, perhaps wearing an olive wreath. Background: The Parthenon on the Acropolis in its prime, painted in original colors, white marble statues, bright blue sky, deep depth of field. Classical beauty, photorealistic, 8k, serene atmosphere.',
    icon: '🏺',
  },
  {
    id: 'aztec-empire',
    name: 'Aztec Empire',
    description: 'Feathers, gold, and Tenochtitlan.',
    prompt: 'Cinematic shot, Tenochtitlan, 1500. The subject is an Aztec warrior or noble, wearing a spectacular headdress with vibrant green quetzal feathers, jade ear spools, and gold jewelry. Background: The Templo Mayor pyramid, canals filled with boats and floating gardens (chinampas). Vibrant colors, tropical atmosphere, detailed textures of stone and feathers, sunlight.',
    icon: '☀️',
  },
  {
    id: 'tang-dynasty',
    name: 'Tang Dynasty',
    description: 'Golden age of Chinese culture.',
    prompt: 'Cinematic shot, Chang\'an, 700 AD. The subject is a noble or scholar, wearing flowing Hanfu silk robes with wide sleeves and intricate embroidery, hair styled in a traditional bun. Background: An imperial palace courtyard with red wooden pillars, curved roofs, and paper lanterns glowing softly at dusk. Traditional Chinese architecture, elegant and majestic, cinematic lighting, rich reds and golds.',
    icon: '🏮',
  },
  {
    id: 'flower-power',
    name: 'Flower Power 60s',
    description: 'Peace, love, and music.',
    prompt: 'Cinematic shot, Woodstock, 1969. The subject is a hippie, wearing a tie-dye shirt, a flower crown, round sunglasses, and peace sign beads. Background: A grassy festival field with a crowd, a painted VW bus, acoustic guitars. Lens flare, warm sunny vibe, film grain, vintage Kodachrome look, nostalgic, colorful.',
    icon: '☮️',
  },
  {
    id: 'fifties-diner',
    name: '50s Rock n Roll',
    description: 'Milkshakes and jukeboxes.',
    prompt: 'Cinematic shot, USA, 1955. The subject is a greaser in a leather jacket and jeans, or a girl in a poodle skirt and saddle shoes. Background: A retro chrome-and-neon diner interior, black and white checkerboard floor, red vinyl booths, a Wurlitzer jukebox, a milkshake on the table. Nostalgic Americana, vibrant colors, bright lighting, rock and roll vibe.',
    icon: '🍔',
  },
  {
    id: 'french-revolution',
    name: 'French Revolution',
    description: 'Liberty, Equality, Fraternity.',
    prompt: 'Cinematic shot, Paris, 1789. The subject is a revolutionary, wearing a phrygian cap, a tricolor cockade, and 18th-century commoner clothes (sans-culottes). Background: A chaotic Paris street with a barricade made of furniture and cobblestones, smoke filling the air, French flags waving. Dramatic lighting, revolutionary spirit, highly detailed, historical intensity.',
    icon: '🇫🇷',
  },
  {
    id: 'industrial-revolution',
    name: 'Industrial Age',
    description: 'Steam power and factories.',
    prompt: 'Cinematic shot, Industrial Era, 1850. The subject is a factory owner in a top hat and frock coat, or a worker in a flat cap and suspenders, face smudged with soot. Background: A massive brick factory interior with giant steam engines, turning gears, brass pipes, and atmospheric steam and smoke. Moody lighting, shafts of light through high windows, steampunk vibe, gritty.',
    icon: '⚙️',
  },
  {
    id: 'maya-jungle',
    name: 'Mayan Jungle',
    description: 'Hidden temples and jade.',
    prompt: 'Cinematic shot, Mayan City, 800 AD. The subject is Maya royalty, wearing jaguar skin, heavy jade jewelry, and body paint. Background: A massive stone step-pyramid rising out of a dense, misty rainforest, shafts of sunlight piercing the canopy, mossy stone textures. Ancient mystery, photorealistic, lush greenery, atmospheric.',
    icon: '🌿',
  },
  {
    id: 'ottoman-empire',
    name: 'Ottoman Empire',
    description: 'Bazaars and minarets.',
    prompt: 'Cinematic shot, Constantinople, 1600. The subject is a merchant or noble, wearing a rich brocade kaftan and an intricate turban. Background: The bustling Grand Bazaar, shelves stacked with colorful spices, Persian carpets, and mosaic glass lamps. Warm ambient lighting, rich textures and intricate patterns, architectural arches, detailed.',
    icon: '🕌',
  },
  {
    id: 'ice-age',
    name: 'Ice Age Tundra',
    description: 'Glaciers and mammoths.',
    prompt: 'Cinematic shot, Pleistocene Epoch. The subject is a primitive human, wrapped in heavy mammoth fur clothing, with frost on their face and hair. Background: A vast, frozen tundra landscape with blue glaciers, a herd of woolly mammoths walking in the distance, aurora borealis in the night sky. Cold blue tones, photorealistic, snow textures, dramatic.',
    icon: '❄️',
  },
  {
    id: 'ancient-babylon',
    name: 'Babylonian Gardens',
    description: 'Hanging gardens of wonder.',
    prompt: 'Cinematic shot, Babylon, 600 BC. The subject is a Babylonian royal, wearing Mesopotamian garments with fringed fabric and gold armbands. Background: The Hanging Gardens of Babylon, terraces overflowing with exotic plants, flowers, and waterfalls, blue glazed brick walls with lion reliefs (Ishtar Gate style). Golden desert sunlight, majestic, lush and vibrant.',
    icon: '🌴',
  },
  {
    id: 'grunge-90s',
    name: '90s Grunge',
    description: 'Flannel, angst, and rock.',
    prompt: 'Cinematic shot, Seattle, 1992. The subject is a grunge rocker, wearing a plaid flannel shirt tied around the waist, ripped jeans, combat boots, and messy hair. Background: A dim basement practice space with band posters on the wall, amplifiers, moody lighting, cigarette smoke. Gritty texture, alternative rock aesthetic, flash photography style.',
    icon: '🎸',
  },
  {
    id: 'y2k-digital',
    name: 'Y2K Hacker',
    description: 'Digital rain and trench coats.',
    prompt: 'Cinematic shot, The Matrix inspired, 1999. The subject is a hacker, wearing a long black leather trench coat, dark sunglasses, and combat boots. Background: A dark, industrial environment with cascading green digital code rain (Matrix code), computer servers, green tint color grading. Cyber-thriller vibe, sharp focus, glossy textures.',
    icon: '💾',
  },
  {
    id: 'golden-hollywood',
    name: 'Golden Hollywood',
    description: 'Red carpets and spotlights.',
    prompt: 'Cinematic shot, Hollywood Premiere, 1935. The subject is a movie star, wearing a sharp tuxedo or a satin evening gown with a fur stole and diamond jewelry. Background: A red carpet event with paparazzi flashbulbs going off, vintage movie palace marquee lights, art deco architecture. Black and white or sepia glamour photography style, soft lighting, elegant.',
    icon: '🎥',
  },
  {
    id: 'atlantis-lost',
    name: 'Lost Atlantis',
    description: 'Underwater kingdom of legend.',
    prompt: 'Cinematic shot, Lost City of Atlantis. The subject is an Atlantean royal, wearing iridescent scale armor and bioluminescent jewelry. Background: Majestic underwater architecture made of pearl, coral, and gold, shafts of sunlight filtering down through deep blue water, schools of glowing fish. Ethereal, magical, 8k resolution, distortion from water.',
    icon: '🧜‍♀️',
  },
  {
    id: 'solarpunk-future',
    name: 'Solarpunk Utopia',
    description: 'Green tech and bright futures.',
    prompt: 'Cinematic shot, Solarpunk Utopia, 2100. The subject is a citizen of the future, wearing futuristic organic clothing made of leaves and light-weaving fabrics. Background: A gleaming city where nature and technology merge, glass towers covered in hanging gardens, wind turbines, solar panels, clear blue sky. Bright, optimistic aesthetic, lush greenery, soft natural light.',
    icon: '🌱',
  },
  {
    id: 'incan-empire',
    name: 'Incan Citadel',
    description: 'High peaks of the Andes.',
    prompt: 'Cinematic shot, Machu Picchu, 1500. The subject is an Incan noble, wearing a colorful woven tunic with geometric patterns and gold ear spools. Background: The iconic stone citadel perched high in the Andes mountains, terraced fields, llamas grazing in the mist, dramatic mountain peaks. Golden hour lighting, atmospheric clouds, detailed stone textures.',
    icon: '🦙',
  },
  {
    id: 'steampunk-sky',
    name: 'Steampunk Skies',
    description: 'Airships and brass gears.',
    prompt: 'Cinematic shot, Steampunk Airship, 1895. The subject is an airship captain, wearing a leather aviator cap, brass goggles, and a mechanical gauntlet. Background: The deck of a flying copper dreadnought soaring above the clouds, spinning propellers, steam venting from brass pipes, clockwork mechanisms. Adventurous, mechanical, golden lighting, detailed metal textures.',
    icon: '🎈',
  },
  {
    id: 'gothic-horror',
    name: 'Gothic Horror',
    description: 'Dark castles and vampires.',
    prompt: 'Cinematic shot, Gothic Horror, 1880. The subject is a vampire hunter or mysterious count, wearing a high-collared black velvet coat and holding a lantern. Background: A crumbling stone castle corridor, thick cobwebs, lightning flashing through a stained-glass window, dark shadows. Eerie, atmospheric, blue and black color palette, spooky.',
    icon: '🦇',
  },
  {
    id: 'scottish-highlands',
    name: 'Scottish Highlands',
    description: 'Mist, moors, and ancient castles.',
    prompt: 'Cinematic shot, Scotland, 1740. The subject is a rugged Highlander warrior, wearing a weathered tartan kilt, leather sporran, and fur cloak, holding a basket-hilted broadsword. Background: Misty, dramatic rolling green highlands, purple heather, a stone circle standing mysteriously in the fog, moody overcast sky. Outlander aesthetic, 8k resolution, raw nature.',
    icon: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  },
  {
    id: 'martian-frontier',
    name: 'Martian Frontier',
    description: 'Life on the Red Planet.',
    prompt: 'Cinematic shot, Mars Colony, 2080. The subject is a futuristic colonist, wearing a sleek, dust-covered EVA suit with a gold-tinted visor reflecting the landscape. Background: The rusted red dunes of Mars, a high-tech geodesic bio-dome city in the distance, two moons in the salmon-pink sky. Harsh realistic lighting, sci-fi masterpiece, red and orange tones.',
    icon: '🪐',
  },
  {
    id: 'bioluminescent-forest',
    name: 'Alien Forest',
    description: 'Glowing flora and eternal night.',
    prompt: 'Cinematic shot, Alien Jungle, Midnight. The subject is an ethereal explorer or native being, with subtle glowing tribal markings on their skin. Background: A dense, magical forest filled with giant phosphorescent mushrooms, hanging vines glowing blue and purple, floating spores like fireflies. Mystical, dreamlike atmosphere, Avatar style, dark background with neon highlights.',
    icon: '🍄',
  },
  {
    id: 'comic-book',
    name: 'Comic Book',
    description: 'Bold lines and heroic poses.',
    prompt: 'Comic book art style, Golden Age. The subject is a superhero, standing heroically with hands on hips, wearing a dynamic costume with a cape fluttering in the wind. Background: A stylized metropolis skyline, dramatic action lines (speed lines), halftone dot shading, bold black outlines, vibrant primary colors, speech bubble "POW!" visual effect. Illustration style.',
    icon: '💥',
  },
  {
    id: 'versailles-court',
    name: 'Royal Versailles',
    description: 'Opulence, wigs, and gold.',
    prompt: 'Cinematic shot, Palace of Versailles, 1770. The subject is French royalty, wearing a towering powdered wig, white face powder, and an extravagant silk gown or velvet coat with gold embroidery. Background: The Hall of Mirrors, reflecting crystal chandeliers, gold leaf detailing, frescoed ceilings. Lavish, decadent Rococo atmosphere, bright and airy, pastel colors.',
    icon: '🍰',
  },
  {
    id: 'arabian-nights',
    name: 'Arabian Nights',
    description: 'Magic carpets and desert stars.',
    prompt: 'Cinematic shot, Ancient Baghdad Legend. The subject is a rogue or princess, wearing flowing silk pants, a vest, and a turban, holding a magic lamp. Background: A moonlit desert city skyline with onion domes and minarets, a flying carpet hovering nearby, starry night sky, magical sparkles. Warm lantern light, deep blues and golds, fantasy style.',
    icon: '🌙',
  },
  {
    id: 'pixel-verse',
    name: 'Pixel Verse',
    description: '8-bit retro gaming world.',
    prompt: 'Pixel art aesthetic, 16-bit RPG. The subject is a pixelated hero character, wearing armor or adventurer clothes. Background: A blocky fantasy world with pixelated trees, fluffy clouds, and a castle in the distance. Vibrant retro color palette, scanline effect, nostalgic gaming vibe, SNES style graphics.',
    icon: '👾',
  },
  {
    id: 'claymation',
    name: 'Clay World',
    description: 'Stop-motion animation style.',
    prompt: 'Claymation stop-motion style. The subject appears to be made of modeling clay with visible fingerprints and soft, rounded textures. Background: A handcrafted miniature set made of felt, cardboard, and clay trees. Shallow depth of field (tilt-shift), warm studio lighting, whimsical Aardman animation look, playful.',
    icon: '🧱',
  },
  {
    id: 'toy-world',
    name: 'Toy World',
    description: 'Living in a macro universe.',
    prompt: 'Macro photography, Toy Story aesthetic. The subject is a high-quality articulated action figure or doll with plastic sheen textures. Background: A giant-scale child\'s bedroom floor, massive wooden blocks, marbles, and fuzzy carpet strands. Bright playful lighting, bokeh effect, sense of scale.',
    icon: '🧸',
  },
  {
    id: 'surreal-dream',
    name: 'Surreal Dream',
    description: 'Melting clocks and floating islands.',
    prompt: 'Surrealist masterpiece. The subject is floating or distorted, perhaps wearing melting clock accessories or a bowler hat. Background: A vast, empty desert landscape with impossible geometry, floating islands, giant eyes in the sky, long shadows. Salvador Dali and Magritte inspired, dreamlike, mysterious, oil painting style.',
    icon: '🎨',
  },
  {
    id: 'retro-anime',
    name: 'Retro Anime',
    description: '90s cel-shaded animation style.',
    prompt: 'Cinematic shot, 1990s Anime style. The subject is drawn in a vintage anime aesthetic with cel-shading, large expressive eyes, and dramatic hair. Background: A detailed hand-painted watercolor background of a city at sunset or a starry night. Film grain, chromatic aberration, retro TV broadcast effect, high quality animation keyframe, emotional.',
    icon: '✨',
  }
];
